Repository Welcome-Bot/welcome-bot, pull requests merged in 2021-06, with the labels that each got.

#3 Server count for discord.boats
  .env.example
  CHANGELOG.md
  src/app.js
  src/functions/serverCount.js
Labels: Priority: medium, Status: Ready, Type: enhancement, Version: minor

#6 Update welcome message
  CHANGELOG.md
  src/functions/greetUser.js
Labels: Priority: medium, Status: Ready, Type: enhancement, Version: minor

#7 rename org
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  CHANGELOG.md
  README.md
  src/app.js
  src/functions/greetUser.js
  src/functions/presence.js
  src/functions/serverCount.js
Labels: Status: Ready

#8 Add docs
  CHANGELOG.md
  README.md
  docs/README.md
  docs/commands.md
  docs/privacy-policy.md
  docs/terms.md
Labels: Priority: high, Status: Ready, Type: enhancement, Updates: documentation, Version: minor

#9 Add mongodb
  .env.example
  .eslintignore
  .eslintrc.json
  .github/workflows/run-format.yml
  CHANGELOG.md
  README.md
  package-lock.json
  package.json
  src/app.js
  src/db/connection.js
  src/db/functions/addServer.js
  src/db/functions/getServer.js
  src/db/functions/removeServer.js
  src/db/functions/updateServer.js
  src/functions/greetUser.js
  src/schema/serverSchema.js
Labels: Priority: medium, Status: Ready

#10 Use mongodb
  CHANGELOG.md
  README.md
  docs/README.md
  docs/commands.md
  docs/privacy-policy.md
  src/app.js
  src/db/functions/addGuild.js
  src/db/functions/addServer.js
  src/db/functions/getGuild.js
  src/db/functions/getServer.js
  src/db/functions/removeGuild.js
  src/db/functions/removeServer.js
  src/db/functions/updateGuild.js
  src/functions/execute.js
  src/schema/guildSchema.js
Labels: Priority: high, Status: Ready, Type: enhancement, Version: minor

#11 Fix errors
  docs/commands.md
  src/functions/execute.js
  src/functions/greetUser.js
Labels: No-changelog, Priority: high, Status: Ready, Type: bug, Version: major

#12 Fix errors
  .env.example
  docs/commands.md
  docs/self-hosting.md
  src/app.js
  src/functions/execute.js
  src/functions/greetUser.js
  src/functions/serverCount.js
Labels: No-changelog, Priority: medium, Status: Ready

#13 Add help
  .env.example
  CHANGELOG.md
  README.md
  docs/commands.md
  docs/privacy-policy.md
  docs/self-hosting.md
  package-lock.json
  src/app.js
  src/commands/admin/channel.js
  src/commands/admin/message.js
  src/commands/admin/prefix.js
  src/commands/bot/help.js
  src/commands/bot/ping.js
  src/commands/bot/test.js
  src/commands/sample/sample.js
  src/db/connection.js
  src/db/functions/addGuild.js
  src/db/functions/dbAuditor.js
  src/db/functions/getGuild.js
  src/db/functions/removeGuild.js
  src/db/functions/updateGuild.js
  src/functions/execute.js
  src/schema/guildSchema.js
Labels: Priority: high, Status: Ready, Type: breaking, Version: minor

#18 v1.3.0
  .env.example
  CHANGELOG.md
  README.md
  docs/README.md
  docs/commands.md
  docs/privacy-policy.md
  docs/self-hosting.md
  docs/terms.md
  src/bot.js
  src/commands/admin/channel.js
  src/commands/admin/message.js
  src/commands/admin/prefix.js
  src/commands/bot/help.js
  src/commands/bot/test.js
  src/commands/info/info.js
  src/commands/info/stats.js
  src/commands/info/user.js
  src/commands/mod/ban.js
  src/commands/mod/kick.js
  src/commands/mod/unban.js
  src/commands/owner/eval.js
  src/commands/owner/reload.js
  src/commands/sample/sample.js
  src/functions/execute.js
  src/functions/genImage.js
  src/functions/greetUser.js
  src/functions/sayGoodBye.js
  src/functions/serverCount.js
Labels: Priority: high, Status: In progress, Type: bug, Type: enhancement, Version: minor

#20 Dev
  CHANGELOG.md
  README.md
  package-lock.json
  package.json
  src/bot.js
  src/commands/admin/channel.js
  src/commands/admin/message.js
  src/commands/admin/prefix.js
  src/commands/bot/help.js
  src/commands/bot/test.js
  src/commands/info/stats.js
  src/commands/info/user.js
  src/commands/info/version.js
  src/commands/mod/ban.js
  src/commands/mod/kick.js
  src/commands/mod/unban.js
  src/commands/owner/restart.js
  src/commands/sample/sample.js
  src/db/functions/dbAuditor.js
  src/db/functions/guild/addGuild.js
  src/db/functions/guild/getGuild.js
  src/db/functions/guild/removeGuild.js
  src/db/functions/guild/updateGuild.js
  src/db/functions/version/addVersion.js
  src/db/functions/version/getVersion.js
  src/functions/execute.js
  src/functions/greetUser.js
  src/functions/sayGoodBye.js
  src/functions/versionSender.js
  src/schema/guildSchema.js
  src/schema/versionSchema.js
Labels: Priority: medium, Status: In progress, Type: bug, Type: enhancement

#22 v1.5
  .env.example
  .npmignore
  CHANGELOG.md
  README.md
  package-lock.json
  package.json
  src/WelcomeBot.js
  src/bot.js
  src/commands/bot/help.js
  src/commands/fun/figlet.js
  src/commands/fun/image.js
  src/commands/fun/pokemon.js
  src/commands/general/help.js
  src/commands/general/invite.js
  src/commands/general/ping.js
  src/commands/info/info.js
  src/commands/info/stats.js
  src/commands/info/user.js
  src/commands/info/version.js
  src/commands/misc/test.js
  src/commands/misc/uptime.js
  src/commands/mod/ban.js
  src/commands/mod/kick.js
  src/commands/mod/unban.js
  src/commands/owner/eval.js
  src/commands/owner/reload.js
  src/commands/owner/restart.js
  src/commands/sample/sample.js
  src/commands/setup/channel.js
  src/commands/setup/enable.js
  src/commands/setup/message.js
  src/commands/setup/prefix.js
  src/functions/execute.js
  src/functions/presence.js
  src/functions/randomImage.js
  src/functions/serverCount.js
  src/functions/uptime.js
  src/functions/versionSender.js
  src/schema/guildSchema.js
Labels: Priority: high, Status: In progress, Type: enhancement, Version: minor

#23 Fix bug: not posting server count to botlist.space
  CHANGELOG.md
  README.md
  package.json
  src/functions/greetUser.js
  src/functions/serverCount.js
Labels: Status: Ready, Type: bug, Version: patch

#25 Upgrade to djs v13
  .github/workflows/run-format.yml
  CHANGELOG.md
  package-lock.json
  package.json
  src/WelcomeBot.js
  src/commands/fun/image.js
  src/commands/fun/pokemon.js
  src/commands/general/help.js
  src/commands/info/info.js
  src/commands/info/stats.js
  src/commands/info/user.js
  src/commands/mod/ban.js
  src/commands/mod/kick.js
  src/commands/mod/unban.js
  src/commands/owner/reload.js
  src/commands/owner/restart.js
  src/commands/setup/enable.js
  src/commands/setup/prefix.js
  src/functions/execute.js
  src/functions/greetUser.js
  src/functions/presence.js
  src/functions/randomImage.js
Labels: Priority: high, Status: Ready, Type: enhancement

#26 v1.6
  .github/workflows/run-format.yml
  CHANGELOG.md
  commands.md
  package-lock.json
  package.json
  src/WelcomeBot.js
  src/bot.js
  src/commandTemplate.js
  src/commands/anime/waifu.js
  src/commands/core/invite.js
  src/commands/core/lib.js
  src/commands/core/ping.js
  src/commands/core/uptime.js
  src/commands/core/website.js
  src/commands/fun/figlet.js
  src/commands/fun/image.js
  src/commands/fun/pokemon.js
  src/commands/games/coinflip.js
  src/commands/general/help.js
  src/commands/general/ping.js
  src/commands/info/botinfo.js
  src/commands/info/stats.js
  src/commands/info/user.js
  src/commands/info/version.js
  src/commands/manage/prune.js
  src/commands/misc/qrcode.js
  src/commands/misc/test.js
  src/commands/mod/ban.js
  src/commands/mod/kick.js
  src/commands/mod/unban.js
  src/commands/owner/eval.js
  src/commands/owner/reload.js
  src/commands/owner/restart.js
  src/commands/setup/channel.js
  src/commands/setup/enable.js
  src/commands/setup/follow.js
  src/commands/setup/message.js
  src/commands/setup/prefix.js
  src/functions/beautifyPerms.js
  src/functions/execute.js
  src/functions/get.js
  src/functions/greetUser.js
  src/functions/presence.js
  src/functions/randomImage.js
  src/functions/serverCount.js
  src/functions/versionSender.js
  src/helpers/cmdTemplate.md
  src/helpers/updateDocs.js
  src/schema/guildSchema.js
Labels: Priority: medium, Status: Ready, Type: enhancement, Version: minor

#27 Fix bugs
  CHANGELOG.md
  package.json
  src/bot.js
  src/commands/info/user.js
Labels: Priority: medium, Status: Ready, Type: bug, Version: patch

#30 v1.7
  .env.example
  CHANGELOG.md
  README.md
  commands.md
  package.json
  src/WelcomeBot.js
  src/bot.js
  src/commandTemplate.js
  src/commands/core/botperms.js
  src/commands/core/ping.js
  src/commands/core/support.js
  src/commands/core/uptime.js
  src/commands/general/help.js
  src/commands/general/perms.js
  src/commands/info/user.js
  src/commands/misc/qrcode.js
  src/commands/mod/ban.js
  src/commands/mod/kick.js
  src/commands/mod/prune.js
  src/commands/mod/unban.js
  src/commands/owner/eval.js
  src/commands/owner/servers-list.js
  src/commands/setup/channel.js
  src/commands/setup/follow.js
  src/commands/setup/message.js
  src/commands/setup/prefix.js
  src/functions/execute.js
  src/functions/genImage.js
  src/functions/greetUser.js
  src/functions/serverCount.js
  src/functions/versionSender.js
  src/helpers/cmdTemplate.md
  src/helpers/updateDocs.js
Labels: Priority: medium, Status: Ready, Type: bug, Type: enhancement, Version: minor

#52 Fix bugs
  CHANGELOG.md
  src/WelcomeBot.js
  src/commands/info/user.js
  src/commands/mod/ban.js
  src/commands/mod/prune.js
  src/commands/mod/unban.js
  src/commands/owner/eval.js
  src/commands/setup/channel.js
  src/commands/setup/disable.js
  src/commands/setup/enable.js
  src/functions/execute.js
  src/functions/greetUser.js
Labels: No-changelog

#55 Fix bug & move hug, kiss, cuddle commands to anime.
  CHANGELOG.md
  commands.md
  src/commands/anime/cuddle.js
  src/commands/anime/hug.js
  src/commands/anime/kiss.js
  src/commands/info/botinfo.js
Labels: Type: bug, Version: minor

#57 Debugging
  CHANGELOG.md
  package.json
  src/WelcomeBot.js
  src/bot.js
  src/functions/execute.js
Labels: Priority: high, Status: Ready, Type: enhancement, Version: patch

#58 Some more debugging
  CHANGELOG.md
  package.json
  src/bot.js
Labels: Version: patch

#59 Dev
  CHANGELOG.md
  package.json
  src/functions/execute.js
  src/loaders/Locale.js
Labels: Version: patch

#60 Dev
  src/bot.js
  src/functions/execute.js
  src/loaders/Locale.js
Labels: Version: patch
